### PR TITLE
Use the python logger

### PR DESCRIPTION
**Pull request by akeeman**
Use the python logging library instead of a print function to handle logging.

Do I have to update any tests? I can't find them.

### CODE REVIEW

**Comment by nino-rasic** [comment]
Hi @akeeman, thanks for the input.

It makes sense to use python logging and we will change it, but in the next major version.

Also, logger in this commit doesn't have any handler so I'm not sure if it would work correctly...for the update we would use configuration that would allow us the same structure of messages we already have, but that shouldn't be a problem.

Best regards

**Comment by akeeman** [comment]
Hi @nino-rasic 

As this is a braking change I totally agree that it should wait for a major version.

Handlers are generally set by the application, as it should be up to the application to determine where the log line will eventually go. Formatting should largely be handled there too. That leaves the indentation to be handled. But this library doesn't change the value of `logdepth` itself, so I don't think this library is the place to handle such indentation. It should be handled by a logging formatter.

```python
import logging
import sys

formatter = logging.Formatter(fmt='%(asctime)s| %(levelname)s |%(message)s')
handler = logging.StreamHandler(stream=sys.stderr)
handler.setFormatter(formatter)
logging.root.addHandler(handler)

logging.getLogger(__name__).info("Hello word")
```
```
$ python my-application.py
2019-07-12 19:42:13,370| INFO |Hello World
```

**Comment by akeeman** [comment]
@nino-rasic Hi, are there any plans for a v3.0 any time soon?

**Comment by akeeman** [comment]
I've added the proposed logger above, so people can replicate existing behavior with minimal effort. Also updated the example file to use that logger.

**Comment by make-ing** [comment]
+1

**Comment by akeeman** [comment]
> _* This logger logs to stderr instead of stdout_

Fix that, so that it's now extremely low impact:

```python
from meteomatics.logger import create_log_handler

create_log_handler(stream=sys.stdout)
```

**Comment by akeeman** [comment]
> @meteomatics Hi, are there any plans for a v3.0 any time soon?

**Comment by meteomatics** [comment]
Hi, we published a new version that removes the custom logging and handles logging using python's `logging` module.

Other fixes and updates were published with this version, so I'm closing this PR.

**Comment by akeeman** [comment]
@meteomatics You why isn't 2.2.0 called 3.0.0? It introduces a few backwards incompatible changes...

**Comment by meteomatics** [comment]
Hi, thank you for your feedback.

The methods removed in version 2.2.0 are not supported by our API anymore so backward incompatibility should be limited to queries that were always failing using version 2.1.0.

Did you refer to some specific method that was removed from the interface?

**Comment by akeeman** [comment]
Well, I guess it depends on how you look at it. Because the package was not integrated with the python logging stuff, but printing it to the screen, you could consider the `print` calls as an output of the script. I hooked into those to prevent them from actually printing to stdout, and instead redirect the contents to the logging system. I can imagine many more users have done this, because the package was misbehaving at this point. That part is broken now.

**Comment by akeeman** [comment]
To be clear, there is no way of correcting this issue, as removing 2.2.0 and adding 3.0.0 would cause its own problems. So it's more a reminder to be more careful next time.
Thank you for using the logging system now.

**Pull request closed without merging**
